name: .NET CI

on:
    push:
        branches:
            - master
    pull_request:
            branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
                dotnet-version: '8.0.x'

        - name: Restore dependencies
          run: dotnet restore
          working-directory: GithubActionsPractice

        - name: Build
          run: dotnet build --no-restore
          working-directory: GithubActionsPractice
        - name: Run Tests
          run: |
            mkdir -p test-results
            dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx"
          working-directory: GithubActionsPractice
        
        - name: Upload Test Report
          uses: actions/upload-artifact@v3
          with:
            name: dotnet-test-report
            path: GithubActionsPractice/**/TestResults/*.trx

        - name: Publish
          run: dotnet publish -c Release -o publish
          working-directory: GithubActionsPractice