name: .NET CI

on:
    push:
        branches:
            - master
    pull_request:
            branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
                dotnet-version: '8.0.x'

        - name: Restore dependencies
          run: dotnet restore
          with:
                work-directory: GithubActionsPractice

        - name: Build
          run: dotnet build --no-restore
          with:
                work-directory: GithubActionsPractice
        - name: Run Tests
          run: dotnet test --no-build --verbosity normal
          with:
                    work-directory: GithubActionsPractice