name: Node CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup node.js v16
      uses: actions/setup-node@v3
      with: 
        node-version: 16
        cache: 'npm'

    - name: Install dependencies
      run: npm install


    - name: Run build
      run: npm run build

    - name: Run tests
      run: |
      mkdir -p reports
      pytest >report/output.log

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: reports/output.log 
